
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proye1_compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFIER = 2;
  public static final int TIMES = 9;
  public static final int BOOL = 26;
  public static final int DIVISION = 12;
  public static final int DELIMETERBLOCK = 19;
  public static final int PARAM = 30;
  public static final int SEMI = 3;
  public static final int BRAKE = 63;
  public static final int FUNC = 28;
  public static final int GRATHER = 41;
  public static final int RPAREN = 16;
  public static final int LPAREN = 15;
  public static final int INTEGER_LITERAL = 17;
  public static final int FALSE = 51;
  public static final int LOWERT = 44;
  public static final int SQUARES = 70;
  public static final int GLOB = 62;
  public static final int ARRAY = 60;
  public static final int COMPARATION = 45;
  public static final int FLOAT = 25;
  public static final int STRINGT = 27;
  public static final int EQ = 37;
  public static final int SQUAREC = 71;
  public static final int LOWER = 43;
  public static final int DMINUS = 6;
  public static final int PRODUCT = 11;
  public static final int NUMBER = 18;
  public static final int MODULUS = 14;
  public static final int COMA = 31;
  public static final int LOC = 61;
  public static final int ABSTRACT = 36;
  public static final int TRUE = 50;
  public static final int PLUS = 4;
  public static final int WHILE = 54;
  public static final int ASIGNINTSARRAY = 20;
  public static final int CHAR = 24;
  public static final int BOOLEAN = 35;
  public static final int INPUT = 67;
  public static final int CHARSTR = 22;
  public static final int SWITCH = 58;
  public static final int FOR = 55;
  public static final int RETURN = 65;
  public static final int ASIGNCHARSARRAY = 21;
  public static final int ELSE = 53;
  public static final int BREAK = 34;
  public static final int DOT = 38;
  public static final int INT = 23;
  public static final int POWER = 13;
  public static final int STRING_LITERAL = 32;
  public static final int EQEQ = 33;
  public static final int NEGATION = 40;
  public static final int EOF = 0;
  public static final int DPLUS = 7;
  public static final int DEFAULT = 64;
  public static final int MINUSW = 8;
  public static final int PRINT = 66;
  public static final int ENDEXPR = 72;
  public static final int MAIN = 29;
  public static final int MINUS = 5;
  public static final int FLOATNUM = 49;
  public static final int IN = 56;
  public static final int OR = 47;
  public static final int error = 1;
  public static final int DIFF = 39;
  public static final int PARENTS = 68;
  public static final int SEP = 48;
  public static final int IF = 52;
  public static final int GRATHERT = 42;
  public static final int PARENTC = 69;
  public static final int CASE = 59;
  public static final int RANGE = 57;
  public static final int AND = 46;
  public static final int UMINUS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "SEMI",
  "PLUS",
  "MINUS",
  "DMINUS",
  "DPLUS",
  "MINUSW",
  "TIMES",
  "UMINUS",
  "PRODUCT",
  "DIVISION",
  "POWER",
  "MODULUS",
  "LPAREN",
  "RPAREN",
  "INTEGER_LITERAL",
  "NUMBER",
  "DELIMETERBLOCK",
  "ASIGNINTSARRAY",
  "ASIGNCHARSARRAY",
  "CHARSTR",
  "INT",
  "CHAR",
  "FLOAT",
  "BOOL",
  "STRINGT",
  "FUNC",
  "MAIN",
  "PARAM",
  "COMA",
  "STRING_LITERAL",
  "EQEQ",
  "BREAK",
  "BOOLEAN",
  "ABSTRACT",
  "EQ",
  "DOT",
  "DIFF",
  "NEGATION",
  "GRATHER",
  "GRATHERT",
  "LOWER",
  "LOWERT",
  "COMPARATION",
  "AND",
  "OR",
  "SEP",
  "FLOATNUM",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "IN",
  "RANGE",
  "SWITCH",
  "CASE",
  "ARRAY",
  "LOC",
  "GLOB",
  "BRAKE",
  "DEFAULT",
  "RETURN",
  "PRINT",
  "INPUT",
  "PARENTS",
  "PARENTC",
  "SQUARES",
  "SQUAREC",
  "ENDEXPR"
  };
}

